apiVersion: apps/v1
kind: Deployment
metadata:
    name: helloworld-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: helloworld
    template:
        metadata:
            labels:
                app: helloworld
        spec:
            nodeSelector:
                hardware: high-spec
            containers:
                - name: k8s-demo
                  image: dellex1984919/demo-nodejs-docker
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 15
                      timeoutSeconds: 30
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 15
                      timeoutSeconds: 30
                  ports:
                      - name: nodejs-port
                        containerPort: 3000
